export const STORAGE_KEYS = {
  apiUrl: "timedata_api_url",
  apiToken: "timedata_api_token",
  lastSyncedSeq: "timedata_last_synced_seq",
  // 纯 UI 展示的“上次同步时间”，不参与任何同步判定（cursor 是 lastSyncedSeq）。
  lastSyncDisplayAt: "timedata_last_sync_at",
  syncFailureCount: "timedata_sync_failure_count",
  clockSkewMs: "timedata_clock_skew_ms",
  cloudSyncEnabled: "timedata_cloud_sync_enabled",
  mergeOvernight: "timedata_merge_overnight",
  sleepCategoryId: "timedata_sleep_category_id",
  schemaNormalizationVersion: "timedata_schema_normalization_version",
  todoWorkbenchSplit: "timedata_todo_workbench_split",
  diarySplit: "timedata_diary_split",
  diaryRefPunchesCollapsed: "timedata_diary_ref_punches_collapsed",
  diaryRefDoneTasksCollapsed: "timedata_diary_ref_done_tasks_collapsed",
  diaryRefQuickNotesCollapsed: "timedata_diary_ref_quick_notes_collapsed",
  todoDoneCollapsed: "timedata_todo_done_collapsed",
  todoInboxCollapsed: "timedata_todo_inbox_collapsed",
  todoScheduledCollapsed: "timedata_todo_scheduled_collapsed",
  todoTrackGroupCollapsed: "timedata_todo_track_group_collapsed",
  galaxyEngine: "timedata_galaxy_engine",
  goalTrayWidth: "timedata_goal_tray_width",
  goalsViewMode: "timedata_goals_view_mode",
  quickNoteComposerDraft: "timedata_quicknote_composer_draft",
  captureComposerDraft: "timedata_capture_composer_draft",
  syncPhaseTimings: "timedata_sync_phase_timings",
  diaryReviewYearRange: "timedata_diary_review_year_range",
  diaryReviewLayoutB: "timedata_diary_review_layout_b",
  diaryReviewMode: "timedata_diary_review_mode",
} as const;
