version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    versioning-strategy: increase-if-necessary
    labels: ["deps"]
    ignore:
      - dependency-name: "@capacitor/*"
        update-types: ["version-update:semver-major"]
    groups:
      patch-and-minor:
        update-types: ["patch", "minor"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels: ["ci", "deps"]
